version: '3.9'
services:
  app:
    container_name: FloodControlService
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - redis
    command: >
      sh -c "/app/main --redis=${REDIS_NAME}:${REDIS_PORT} --limit=${K_CALLS_LIMIT} --interval=${N_INTERVAL_SECONDS}"
  redis:
    image: "redis:alpine"
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 2s
      timeout: 10s
      retries: 5
